version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    command: bash "entrypoint.sh"
    volumes:
      - .:/home/node/app
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

#    networks:
#      - keycloak_network
#
#networks:
#  keycloak_network:
#    driver: bridge